name: Postmerge CI
run-name: Testing Github actions 🚀
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo lint step is running ... 
  
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - run: echo build step is running 
      - name: Compile binary
        run: |
          echo "Compiling binary"
          echo "Binary compiled"
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo test step is running ... 

  publish:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    steps:
      - run: echo publish step is running ... 
