name: Postmerge CI
run-name: Linting, building, testing and publishing 🚀

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo lint step is running ... 
  
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - run: echo build step is running 
      - name: Compile binary
        run: |
          echo "Compiling binary"
          echo ${{ github.head_ref}} >>  binary-${{ github.sha }}
          echo "Binary compiled"
      - uses: actions/upload-artifact@v3
        with:
          name: binary-${{ github.sha }}
          path: ./binary-${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo test step is running ... 

  call_publish:
    uses: ./.github/workflows/publish.yaml
    needs: [lint, build, test]
