name: Reusable Publish workflow
run-name: Publish artifacts 🚀
on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo publish step is running ... 
