name: Publish Build Artifacts
run-name: Publish artifacts 🚀
on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish artifacts
        run: echo publish step is running for ${{ github.head_ref }}.${{ github.sha }}...
