name: Publish Build Artifacts
run-name: Publish artifacts 🚀
on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: binary-${{ github.sha }}
          path: ./binary-${{ github.sha }}
      - name: Publish artifacts
        run: |
          echo publish step is running for ${{ github.head_ref }}.${{ github.sha }}...
          cat ./binary-${{ github.sha }}/binary-${{ github.sha }}
