name: Publish Build Artifacts
run-name: Publish artifacts 🚀
on:
  workflow_call:

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        # uses: actions/download-artifact@v2
        # with:
        #   name: binary-${{ github.sha }}
        run: |
          ARCHIVE_URL=$(curl --request GET \
          --url https://api.github.com/repos/CepstrumLabs/actions-playground/actions/artifacts \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header "Accept: application/vnd.github+json" \
          --header 'X-GitHub-Api-Version: 2022-11-28' |  jq '.artifacts[] | select(.name == "binary-${{ github.sha }}") | {archive_download_url}')
          

      - name: Publish artifacts
        run: |
          echo publish step is running for ${{ github.head_ref }}.${{ github.sha }}...
          cat ./binary-${{ github.sha }}
